[project]
name = "doom-clone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "autopep8>=2.3.2",
    "pycodestyle>=2.12.1",
    "pygame>=2.6.1",
    "tomli>=2.2.1",
]
